Feature/auth
PROCOLLAB-github/api pull request #100
Opened 2023-03-06 15:03 UTC by Pichcher

in UserList override get with check for authenticated

2023-03-06 15:05 UTC, Yakser approved these changes
супер, красавчик

2023-03-06 16:21 UTC, VeryBigSad requested changes
сделай отдельный класс IsAuthenticatedOrWriteOnly и юзай его, метод гет верни каким был

2023-03-06 16:21 UTC, VeryBigSad commented on users/views.py
> -    permission_classes = [AllowAny]  # FIXME: change to IsAuthorized
почему? тут надо поменять

2023-03-06 16:21 UTC, VeryBigSad commented on users/views.py
>          email_body = "Hi, {} {}! Use link below for reset password {}".format(
почему бы не использовать fstrings здесь

2023-03-06 16:21 UTC, VeryBigSad commented on users/views.py
> -    permission_classes = [AllowAny]  # FIXME: change to IsAuthorized
сделать отдельный класс для этого, где если post запрос - пропускать, если нет - не пропускать

2023-03-06 16:21 UTC, VeryBigSad commented on users/views.py
> +                             "you can't create achievements for other people"
это точно по black formatter и flake8?

2023-03-06 19:18 UTC, Yakser approved these changes

2023-03-06 19:19 UTC, Yakser commented on users/views.py
>          email_body = "Hi, {} {}! Use link below for reset password {}".format(
@stolzor должен пофиксить

2023-03-06 19:19 UTC, Yakser commented on users/views.py
> +                             "you can't create achievements for other people"
раз линтеры прогнались то да)

2023-03-06 19:40 UTC, VeryBigSad approved these changes
кайф

2023-03-07 13:32 UTC, stolzor commented on users/views.py
>          email_body = "Hi, {} {}! Use link below for reset password {}".format(
Уже можно начинать?

2023-03-07 13:33 UTC, Yakser commented on users/views.py
>          email_body = "Hi, {} {}! Use link below for reset password {}".format(
да)

2023-03-07 13:34 UTC, merged