Feature/events tests
PROCOLLAB-github/api pull request #103
Opened 2023-03-11 20:07 UTC by XataBq

Изменения в events.tests, добавлены тесты создания event(is_staff, not_is_staff, with_empty_data), update event

2023-03-12 07:46 UTC, Yakser requested changes
супер, но надо капельку порефакторить

2023-03-12 07:46 UTC, Yakser commented on events/tests.py
> +        news = Event.objects.get(id=event_id)
events а не news

2023-03-12 07:46 UTC, Yakser commented on events/tests.py
> +        request = self.factory.patch(f"event/{news.pk}/", {"text": "New text"})
тоже news)

2023-03-12 07:46 UTC, Yakser commented on events/tests.py
> +        response = self.event_detail_view(request, pk=news.pk)
тоже news

2023-03-12 07:46 UTC, Yakser commented on events/tests.py
> +        self.title = "TITLE"
константы именуются заглавными буквами- self.TITLE и тд

2023-03-14 13:58 UTC, VeryBigSad commented
выглядит классно

2023-03-20 13:36 UTC, merged