Feature/events/serializers
PROCOLLAB-github/api pull request #122
Opened 2023-04-04 15:48 UTC by Pichcher

In events/serializers added fields for serializers

2023-04-10 07:42 UTC, Yakser requested changes

2023-04-10 07:42 UTC, Yakser commented on procollab/settings.py
сделай пулл из дева в эту ветку чтобы изменения не затирались

2023-04-10 07:42 UTC, Yakser commented on events/serializers.py
>          ]
registered users не должно быть разве? + сериалайзер для них заюзать

2023-04-14 17:02 UTC, afarut commented on events/serializers.py
>          ]
likes надо убрать, для них написан отдельный класс

2023-04-15 15:05 UTC, Yakser requested changes
чекни комменты

2023-04-15 15:05 UTC, Yakser commented on events/serializers.py
>          ]
> 

нужно возвращать скорее количество лайков а не всю инфу по каждому лайку

2023-04-21 17:49 UTC, merged