Feature/logging prometheus
PROCOLLAB-github/api pull request #163
Opened 2023-07-14 12:52 UTC by afarut

# Метрики

## Внес изменения в докер

Добавил графану, работает на 3000 порту. Node-exporter для отслеживания метрик систем и сам Prometheus для сбора метрик. Добавил "web" (название контейнера) в переменную ALLOWED_HOSTS по просьбе Prometheus.

## Проверка кода

Проверка работоспособности, т.к. много кода я не писал.

## Дополнительная информация

В планах настроить nginx, чтобы графана работала на основном порте сервиса и добавить отслеживание метрик для нескольких самых популярных моделей.

2023-07-15 15:50 UTC, VeryBigSad approved these changes
кайфы

2023-07-15 15:50 UTC, VeryBigSad commented on docker-compose.yml
> +    image: grafana/grafana:8.5.3-ubuntu
графана лейтест мб?

2023-07-15 15:50 UTC, VeryBigSad commented on procollab/settings.py
> +)
Странно, что это нужно указывать в настройках
Я бы такие бакеты поставил, но в целом as you wish
0.1
0.5
1
3
5
10
>10

2023-07-15 15:51 UTC, VeryBigSad commented
Еще, если у тебя жалуется линтер, то ты, кажется, не подключил pre-commit хуки, они должны будут перед коммитом форматировать все файлики и проверять их на всякое полезное. В ридми написано, как установить, полезная штука

2023-07-15 15:53 UTC, Yakser approved these changes
круто, надеюсь заведётся

2023-07-18 12:44 UTC, VeryBigSad approved these changes
кайф

2023-07-25 20:03 UTC, Yakser requested changes
не работает
![image](https://github.com/PROCOLLAB-github/api/assets/53031664/097899b9-fff8-4f8c-a90b-700b0d87c911)
+ скрыты роуты prometheus

2023-09-09 18:55 UTC, merged