Фильтрация по имени и фамилии
PROCOLLAB-github/api pull request #192
Opened 2023-09-10 20:50 UTC by Yakser

# Фильтрация по имени и фамилии

2023-09-10 21:02 UTC, afarut approved these changes
Удачи проду

2023-09-10 22:16 UTC, afarut reviewed
Надо изменить файл docker-compose.prod-ci.yml

2023-09-11 10:58 UTC, VeryBigSad requested changes
Сделайте, чтобы логи выкидывались из докера на основную машину, и будет кайф

2023-09-11 10:58 UTC, VeryBigSad commented on docker-compose.dev-ci.yml
> +  prom-configs:
а где volume с логами будет

2023-09-11 10:58 UTC, VeryBigSad commented on procollab/settings.py
> +    "retention": "10 days",
мб 30 дней лучше
место на диске бесплатное (ну почти)

2023-09-13 12:00 UTC, VeryBigSad approved these changes

2023-09-13 16:32 UTC, merged