export to xslx without db
PROCOLLAB-github/api pull request #193
Opened 2023-09-17 08:49 UTC by koshakkkq

# Краткое название
Экспорт в эксель без бд(доделаю поозже)

## Описание изменений
Сделал все кроме сохранения полей для экспорта в бд
_Опишите изменения, которые вы внесли в код. Не забывайте указывать номер задачи или ссылку на тикет._

## Проверка кода

Чекнуть структуру проекта. Templates в partner_programs норм хранить?

2023-09-17 08:53 UTC, koshakkkq commented on partner_programs/admin.py
> +        ]
Наверное стоит сделать post_migrate для записи в бд начальных значений из словаря.

2023-09-17 09:30 UTC, Yakser requested changes

2023-09-17 09:30 UTC, Yakser commented on partner_programs/templates/admin/partner_programs/fields_choice.html
> +{% extends "admin/base.html" %}
темплейты нужно в папочку templates

в этом случае templates/partner_programs/...

2023-09-17 09:30 UTC, Yakser commented on partner_programs/templates/admin/partner_programs/profiles_change_list.html
> +    <input type="submit" value="Export data." />
value у input'a нужно перевести на русский, т.к. вся админка в основном на русском

2023-09-19 19:35 UTC, Yakser requested changes
перенести кнопку на страничку программы + пофиксить логику построения таблички(брать name из схемы программы)

2023-09-20 13:23 UTC, merged