Feature/mailing
PROCOLLAB-github/api pull request #199
Opened 2023-09-27 12:29 UTC by koshakkkq

# Краткое название

## Описание изменений

Добавил класс с рассылкой.
А есть смысл в использовании celery? Django вроде замечательно делает рассылку. Тут исключительно рассылка с django. Я не вижу особо смысл прикручивать celery

## Тестирование

_Опишите, как тестировали свои изменения. Например, какие тесты проходят, а какие нет._

## Проверка кода

_Опишите, как проверить ваш код._

## Дополнительная информация

_Здесь вы можете добавить какую-либо дополнительную информацию о своих изменениях._

2023-09-27 12:30 UTC, koshakkkq commented on mailing/utils.py
> +        mail.send_mail("My subject", plain_msg, None, emails, html_message=html_msg)
Этого вроде хватает с головой для наших целей. Останется прикрутить кнопки в админку для рассылки по определённым юзерам.

2023-09-27 12:33 UTC, koshakkkq commented on mailing/utils.py
> +        mail.send_mail("My subject", plain_msg, None, emails, html_message=html_msg)
sending rendered template with ~~template_text  ~~arg. Тут template_context

2023-09-28 09:50 UTC, Yakser requested changes
много доработок еще, но в целом кайф. хочется протестить

2023-09-28 09:50 UTC, Yakser commented on mailing/apps.py
> +    name = "mailing"
нет verbose_name

2023-09-28 09:50 UTC, Yakser commented on mailing/tasks.py
> +@shared_task
раз без селери тестим то всё что с селери утащить надо в отдельную ветку (типа на бэкап)))

2023-09-28 09:50 UTC, Yakser commented on mailing/utils.py
> +        plain_msg = strip_tags(html_msg)
текстовую версию будет брать из файликов сбилженных

2023-09-28 09:50 UTC, Yakser commented on procollab/settings.py
> +    "CELERY_BROKER_URL", cast=str, default="redis://localhost:6379/0"
REDIS_HOST вместо localhost:6379

2023-09-29 08:31 UTC, VeryBigSad reviewed
Не нашел сильных проблем - все классно! Написал кучу придирок)
Можешь зафиксить иссуе Сережи и думаю будет норм.

2023-09-29 08:31 UTC, VeryBigSad commented on README.md
> +Run celery scheduler via `celery -A procollab beat`
указать бы, что это не обязательно для всего функционала проект
+ можно указать инструкцию к запуску через докеркомпоз

2023-09-29 08:31 UTC, VeryBigSad commented on mailing/admin.py
поудалять бы все пустые файлы, как `admin.py` и `models.py`, если не планируется моделек создавать

2023-09-29 08:31 UTC, VeryBigSad commented on mailing/views.py
> +def some_task(request):
переименовать бы...

2023-09-29 08:31 UTC, VeryBigSad commented on procollab/celery.py
> +
тут точно все по pep8?

2023-09-29 08:31 UTC, VeryBigSad commented on procollab/settings.py
> +CELERY_TASK_TIME_LIMIT = 30 * 60
30 минут? Может, часа 4 поставим?
Хотя по best practiсe так и так надо будет пересоздавать таски для сверх больших задач, так что норм

2023-09-29 08:31 UTC, VeryBigSad commented on procollab/settings.py
> +        "LOCATION": f"redis://{REDIS_HOST}:6379",
мб redis port тоже в конфиг засунуть

2023-09-30 12:04 UTC, koshakkkq commented
Бтв не удалил селери пока

2023-09-30 12:10 UTC, koshakkkq commented on mailing/views.py
> +
/mailing_test/send_email - Добавил страницу и шаблон для рассылок, те кто будут добавлять кнопки в админке будут юзать класс MailingSchemaView(чуть позже напишу пример взаимодействия). Тут пока для примера id схемы 1.

2023-09-30 12:10 UTC, koshakkkq commented on mailing/models.py
> +        return self.name
Тут храним схему для отправки, шаблон имя и схема полей шаблона в json, например:
`{"key_with_default": {"title": "Ключи с дефолтным значением", "default": "Дефолт знач"}, "simple_key": {"title": "просто ключик"}}`

2023-09-30 12:13 UTC, koshakkkq commented
Тут понятно ещё не всё, нужно по функционалу проверить, а потом я подрефакторю

2023-09-30 13:44 UTC, koshakkkq commented
А поч тесты падают кстати)?

2023-10-01 14:31 UTC, Yakser commented on procollab/celery.py
> +
да, дефолтный файлик с конфигурацией селери

2023-10-07 21:35 UTC, VeryBigSad approved these changes
Все хорошо, нашел только придирки

2023-10-07 21:35 UTC, VeryBigSad commented on mailing/admin.py
> +        "id",
поиск по id зачем

2023-10-07 21:35 UTC, VeryBigSad commented on mailing/models.py
> +        return f"MailingSchema<{self.name}>"
лучше сделать читабельный __str__, но опицонально в целом

2023-10-07 21:35 UTC, merged

2023-10-07 21:36 UTC, Yakser commented on mailing/admin.py
> +        "id",
ну хочется))