swagger doc fix, convert to correct with generics functions view
PROCOLLAB-github/api pull request #237
Opened 2023-11-12 22:55 UTC by LolAnthony

33 task(swagger doc fix)

there is no errors with serializers in console

2023-12-10 17:56 UTC, Yakser reviewed
все кул, но нужно убедиться что замена pk на id не поломает ничего, надо посмотреть есть ли места в коде которые ждут именно pk

2023-12-10 18:13 UTC, Yakser approved these changes
протестил личные и проектные чаты - они живы

2023-12-12 08:55 UTC, VeryBigSad requested changes
все отлично, только 2 минорных фикса и будет прям замечательно!

2023-12-12 08:55 UTC, VeryBigSad commented on chats/views.py
> +            assert "_" in self.kwargs["id"], "pk must contain underscore"
тут бы тоже в доке поменять pk -> id

2023-12-12 08:55 UTC, VeryBigSad commented on partner_programs/views.py
>              data["is_user_member"] = is_user_member
неприятное
В целом не в пиарнике, но хотелось бы этот тех долг убрать, просто добавить его в оба сериалайзера дефолтным значением

2024-02-25 22:42 UTC, merged