added models of criteria and project rating
PROCOLLAB-github/api pull request #262
Opened 2024-02-07 12:26 UTC by sh1nkey

# Краткое название

## Описание изменений

_Опишите изменения, которые вы внесли в код. Не забывайте указывать номер задачи или ссылку на тикет._

## Тестирование

_Опишите, как тестировали свои изменения. Например, какие тесты проходят, а какие нет._

## Проверка кода

_Опишите, как проверить ваш код._

## Дополнительная информация

_Здесь вы можете добавить какую-либо дополнительную информацию о своих изменениях._

2024-02-07 15:17 UTC, Yakser requested changes

2024-02-07 15:17 UTC, Yakser commented on rate_projects/apps.py
> +class RateProjectsConfig(AppConfig):
по неймингу не уверен. RateProjects звучит как "Оцени проекты"
я б подумал над более понятным названием
первое что приходит в голову "ProjectRates"

2024-02-07 15:17 UTC, Yakser commented on rate_projects/constants.py
> +get_type = {
я бы переименовал в RATE_TYPES_MAPPING или что то около того

2024-02-07 15:17 UTC, Yakser commented on rate_projects/constants.py
> +TYPES = (
как насчет VERBOSE_RATE_TYPES? просто types мега абстрактно звучит

2024-02-07 15:17 UTC, Yakser commented on rate_projects/models.py
> +
уф пустая строчка))

2024-02-07 15:17 UTC, Yakser commented on rate_projects/models.py
> +    name = models.CharField(
а вот тут перед name я б ту пустую строчку добавил))

2024-02-07 15:17 UTC, Yakser commented on rate_projects/models.py
> +
не крит но тоже пустая строка зачем то, мб либо без них совсем будем либо разделим по смыслу поля этими пустыми строками

2024-02-09 20:21 UTC, Yakser submitted a review, later dismissed
в целом ок, но есть нужно косметические доработочки внести и разобраться с полями value_*

2024-02-09 20:21 UTC, Yakser commented on rate_projects/models.py
> +        value_str: IntegerField for value
IntegerField везде написано вместо корректных значений

2024-02-09 20:21 UTC, Yakser commented on rate_projects/models.py
> +class ProjectScore(models.Model):
так в итоге юзаем rate или score?

2024-02-09 20:21 UTC, Yakser commented on rate_projects/constants.py
> +VERBOSE_NAME_TYPES = (
может на VERBOSE_TYPES переименуем?

2024-02-09 20:21 UTC, Yakser commented on rate_projects/models.py
> +    value_int = models.IntegerField(
мы можем хранить просто строковое значение и в зависимости от типа критерия его по разному интерпретировать

2024-02-10 02:07 UTC, sh1nkey commented on rate_projects/constants.py
> +get_type = {
исправил на GET_TYPE_FROM_STRING

2024-02-10 02:08 UTC, sh1nkey commented on rate_projects/constants.py
> +TYPES = (
отлично, так и переименовал

2024-02-10 02:10 UTC, sh1nkey commented on rate_projects/constants.py
> +VERBOSE_NAME_TYPES = (
хорошо, на VERBOSE_TYPES

2024-02-12 03:52 UTC, sh1nkey commented on rate_projects/models.py
> +    value_int = models.IntegerField(
исправил

2024-02-12 03:53 UTC, sh1nkey commented on rate_projects/constants.py
> +VERBOSE_NAME_TYPES = (
теперь точно исправил

2024-02-12 03:58 UTC, sh1nkey commented on rate_projects/models.py
> +        verbose_name="Значение с плавающей запятой", max_length=50, null=True, blank=True
убрал

2024-02-13 16:28 UTC, sh1nkey commented on rate_projects/apps.py
> +class RateProjectsConfig(AppConfig):
переделал

2024-02-13 17:27 UTC, Yakser approved these changes

2024-02-13 17:52 UTC, merged