Flexivanov237 pro 173
PROCOLLAB-github/api pull request #281
Opened 2024-02-17 13:41 UTC by sh1nkey

2024-02-17 14:25 UTC, Yakser requested changes

2024-02-17 14:25 UTC, Yakser commented on feed/constants.py
> +FEED_SERIALIZER_MAPPING: Dict[FeedItemType, serializers.Serializer] = {
зачем заменил на Dict?

2024-02-17 14:25 UTC, Yakser commented on feed/constants.py
> +SupportedModel = Union[News | Project | Vacancy]
Что это? Зачем тут Union, вообще неверное его использование. Можно его просто убрать

2024-02-17 14:25 UTC, Yakser commented on feed/constants.py
> +SupportedQuerySet = QuerySet[News | Project | Vacancy]
То же самое

2024-02-17 14:25 UTC, Yakser commented on feed/helpers.py
> +) -> Tuple[List[SupportedQuerySet], int]:
List избыточен

2024-02-17 14:29 UTC, sh1nkey commented on feed/constants.py
> +FEED_SERIALIZER_MAPPING: Dict[FeedItemType, serializers.Serializer] = {
сейчас всё заменю обратно. прочитал неактуальную информацию о том, что typing использовать считается лучше. это было актуально до python 3.9. так что сейчас заменю все эти вот штуки на классические типы

2024-02-17 14:31 UTC, sh1nkey commented on feed/constants.py
> +SupportedModel = Union[News | Project | Vacancy]
бля да я напутал, исправлю

2024-02-17 14:39 UTC, sh1nkey commented on feed/helpers.py
> +) -> Tuple[List[SupportedQuerySet], int]:
если подушнить, то тут list показывает, что кверисет подгрузился в память, потому что обёртывание queryset в list() вызывает подгрузку queryset'а в память
![image](https://github.com/PROCOLLAB-github/api/assets/110509023/1b41115f-884b-48f7-8850-2a5600447e6c)

2024-02-17 20:18 UTC, Yakser requested changes
есть несколько крупных замечений которые надо поправить

2024-02-17 20:18 UTC, Yakser commented on feed/helpers.py
> +def add_pagination(queryset: list[dict], count: int) -> dict:
paginate_queryset не удастся заюзать тут?

2024-02-17 20:18 UTC, Yakser commented on feed/helpers.py
> +def add_pagination(queryset: list[dict], count: int) -> dict:
посмотри по коду в других вьюшках

2024-02-17 20:18 UTC, Yakser commented on vacancy/serializers.py
> +    required_skills = serializers.SerializerMethodField()
это разве не тот старый твой фикс который опять сломает создание вакансий?

2024-02-17 20:18 UTC, Yakser commented on feed/views.py
> +        if "news" in filter_queries:
вроде есть мапа с модельками, можно такую же завести для этого фильтра. либо все делать через одну мапу, но надо заложиться на то что новые типы новостей будут появляться. сто проц забудем что нибудь тут поправить потом

2024-02-17 20:18 UTC, Yakser commented on feed/helpers.py
> +    return {"count": count, "results": queryset, "next": "0", "previous": "0"}
не уверен что ок так хардкодить

2024-02-17 20:18 UTC, Yakser commented on feed/helpers.py
> +    paginator = Paginator(queryset, 3)
что такое 3?)

2024-02-17 20:18 UTC, Yakser commented on feed/helpers.py
> +    if model == Project:
как насчет того, чтобы заюзать match/case?

2024-02-17 20:18 UTC, Yakser commented on feed/helpers.py
> +            .prefetch_related("content_object", "files")
content_object точно должен быть в prefetch? судя по тому что он в единственном числе написан, то это не m2m поле

2024-02-17 20:18 UTC, Yakser commented on feed/serializers.py
> +    type_model = serializers.ChoiceField(choices=constants.FeedItemType, required=True)
model_type?

2024-02-17 20:18 UTC, Yakser commented on feed/views.py
> +        queryset_ready, total_pages = self.get_queryset(models_to_get, page_number)
ачё почему именно ready?

2024-02-17 20:18 UTC, Yakser commented on feed/views.py
> +    def get_queryset(
забавно что get_queryset возвращает вообще не QuerySet, а два каких-то значения
это сто процентов надо исправить, потому что get_queryset во вьюшках юзается много где под капотом и важно чтобы там был реально QuerySet

2024-02-17 20:18 UTC, Yakser commented on partner_programs/admin.py
> +        # Определим даты 1 ноября и 12 февраля
huh?

2024-02-17 20:20 UTC, Yakser commented on feed/helpers.py
> +) -> Tuple[List[SupportedQuerySet], int]:
оке, согласен

2024-02-18 06:04 UTC, sh1nkey commented on feed/helpers.py
> +    return {"count": count, "results": queryset, "next": "0", "previous": "0"}
ты про next и previous? если да, то Егор сказал, что так можно

2024-02-18 06:04 UTC, sh1nkey commented on feed/helpers.py
> +            .prefetch_related("content_object", "files")
он - в Generic Relation, а оно почему-то достаётся через prefetch_related()

2024-02-19 05:38 UTC, gregor-tokarev commented on feed/helpers.py
> +    return {"count": count, "results": queryset, "next": "0", "previous": "0"}
@Yaksert действительно я виновен, мы во фронте по сути не испльзуем next и previous. Но чисто для типизации и совместимостью с paginate_queryset лучше чтобы просто пустые строки

2024-02-19 05:49 UTC, Yakser commented on feed/helpers.py
> +    return {"count": count, "results": queryset, "next": "0", "previous": "0"}
Мб есть PaginateSerializer в который можно эти данные положить? Ок если нужна совсестимость, не ок хардкодить ключи словаря вот так, когда скорее всего есть сериалайзер

2024-02-19 05:51 UTC, gregor-tokarev commented on feed/helpers.py
> +    return {"count": count, "results": queryset, "next": "0", "previous": "0"}
Да так будет лучше, но если это какое-то время большее 10 минут займет, то это можно и после релиза ленты в прод сделать.

2024-02-19 10:54 UTC, sh1nkey commented on vacancy/serializers.py
> +    required_skills = serializers.SerializerMethodField()
[объяснял в прошлом]

2024-02-19 10:54 UTC, sh1nkey commented on feed/views.py
> +        if "news" in filter_queries:
сделал

2024-02-19 10:55 UTC, sh1nkey commented on feed/helpers.py
> +    paginator = Paginator(queryset, 3)
забей

2024-02-19 11:04 UTC, sh1nkey commented on feed/helpers.py
> +def add_pagination(queryset: list[dict], count: int) -> dict:
сделал

2024-02-19 11:04 UTC, sh1nkey commented on vacancy/serializers.py
> +    required_skills = serializers.SerializerMethodField()
бля надо бы это в будущем подправить, кншн

2024-02-19 11:05 UTC, sh1nkey commented on feed/helpers.py
> +    return {"count": count, "results": queryset, "next": "0", "previous": "0"}
пох исправил

2024-02-19 11:05 UTC, sh1nkey commented on feed/serializers.py
> +    type_model = serializers.ChoiceField(choices=constants.FeedItemType, required=True)
переименовал, потому что вроде как линтер ругался на не оч правильный нейминг

2024-02-19 11:05 UTC, sh1nkey commented on feed/views.py
> +        queryset_ready, total_pages = self.get_queryset(models_to_get, page_number)
ну типа обработанный, не нужно его сериализовывать

2024-02-19 11:06 UTC, sh1nkey commented on feed/views.py
> +    def get_queryset(
исправил

2024-02-19 14:59 UTC, Yakser requested changes

2024-02-19 14:59 UTC, Yakser commented on feed/constants.py
> +model_mapping = {"news": News, "project": Project, "vacancy": Vacancy}
не хочешь тут заюзать FeedItemType?

2024-02-19 14:59 UTC, Yakser commented on feed/helpers.py
> +# def paginate_model_items(
коммент не нужен кажется

2024-02-19 14:59 UTC, Yakser commented on feed/serializers.py
> +    type_model = serializers.ChoiceField(choices=constants.FeedItemType, required=True)
непон, как так
покажи ошибку плиз

2024-02-19 14:59 UTC, sh1nkey commented on feed/helpers.py
> +def add_pagination(queryset: list[dict], count: int) -> dict:
сделал

2024-02-19 14:59 UTC, Yakser commented on feed/constants.py
> +model_mapping = {"news": News, "project": Project, "vacancy": Vacancy}
вот как то пипец хочется одну эту мапу юзать, с ключами которые задаются в enum'е

2024-02-19 15:10 UTC, sh1nkey commented on vacancy/serializers.py
> +    required_skills = serializers.SerializerMethodField()
поправил

2024-02-19 15:11 UTC, sh1nkey commented on partner_programs/admin.py
> +        # Определим даты 1 ноября и 12 февраля
бля поправил

2024-02-19 15:11 UTC, Yakser commented on feed/views.py
> +        queryset_ready, total_pages = self.get_queryset(models_to_get, page_number)
а какой кверисет нужно сериализовывать? вообще тут непонятно

2024-02-19 18:38 UTC, sh1nkey commented on feed/constants.py
> +model_mapping = {"news": News, "project": Project, "vacancy": Vacancy}
исправил в новом коммите исправил

2024-02-19 19:14 UTC, Yakser requested changes

2024-02-19 19:14 UTC, Yakser commented on feed/views.py
> +        serialized_paginated_data, sum_pages = self.paginate_serialize_data(
serialized_paginated_data -> prepared_data

2024-02-19 19:14 UTC, Yakser commented on feed/helpers.py
> +        else 10
почему 10? унести в константы надо, через 2 секунды забудешь че за 10)

2024-02-19 19:14 UTC, Yakser commented on feed/helpers.py
> +def paginate_serialize_feed(
тоже конечно тяжко звучит

2024-02-19 19:14 UTC, Yakser commented on feed/helpers.py
> +    model_data: dict[SupportedQuerySet], paginator: LimitOffsetPagination, request, view
а тайпинги для request и view?)

2024-02-19 19:14 UTC, Yakser commented on feed/helpers.py
> +def paginate_serialize_feed_queryset(
тоже часть тайп хинтов пропала(,  для request точно есть норм тип, для модельки и вьюшки уже хз

2024-02-19 19:14 UTC, Yakser commented on feed/helpers.py
> +    result.extend(to_feed_items(model, paginated_data))
непон, ты мутируешь аргумент, который приходит в функцию? 
так очень нельзя делать)

2024-02-19 19:14 UTC, Yakser commented on feed/helpers.py
> +    result.extend(to_feed_items(model, paginated_data))
и 6 аргументов у функции тоже не ок совершенно

2024-02-19 19:14 UTC, Yakser commented on feed/helpers.py
> +    result.extend(to_feed_items(model, paginated_data))
и неочевидно что функция возвращает

2024-02-19 19:14 UTC, Yakser commented on feed/serializers.py
> +class PagTestSerializer(serializers.Serializer):
PagTest?

2024-02-19 19:56 UTC, sh1nkey commented on feed/views.py
> +        serialized_paginated_data, sum_pages = self.paginate_serialize_data(
исправил

2024-02-19 19:56 UTC, sh1nkey commented on feed/helpers.py
> +        else 10
исправил

2024-02-19 19:57 UTC, sh1nkey commented on feed/helpers.py
> +def paginate_serialize_feed(
да норм, оно ж используется всего 1 раз

2024-02-19 19:58 UTC, sh1nkey commented on feed/helpers.py
> +def paginate_serialize_feed_queryset(
добавил

2024-02-19 19:58 UTC, sh1nkey commented on feed/helpers.py
> +    model_data: dict[SupportedQuerySet], paginator: LimitOffsetPagination, request, view
добавил

2024-02-19 19:59 UTC, sh1nkey commented on feed/serializers.py
> +class PagTestSerializer(serializers.Serializer):
удалил

2024-02-19 19:59 UTC, sh1nkey commented on feed/helpers.py
> +    result.extend(to_feed_items(model, paginated_data))
вроде тоже исправил?...

2024-02-19 20:10 UTC, Yakser commented on feed/constants.py
> +model_mapping = {
ето константа - большими буковками надо)

2024-02-19 20:10 UTC, Yakser commented on feed/helpers.py
> +def paginate_serialize_feed(
ну энивей громоздко

2024-02-19 20:11 UTC, Yakser reviewed
мелкие замечания есть но в целом норм)

2024-02-19 20:12 UTC, Yakser reviewed
мелкие замечания есть но в целом норм)

2024-02-19 20:12 UTC, Yakser approved these changes
мелкие замечания есть но в целом норм)

2024-02-19 20:13 UTC, merged