Перевод навыков и допиливание специализаций на новые в датасетах
PROCOLLAB-github/api pull request #317
Opened 2024-03-03 15:04 UTC by IgorDuino

# Краткое название
Перевод навыков и допиливание специализаций на новые в датасетах

## Описание изменений

Миграция навыков пользователей и необходимых навыков для вакансий
Адаптация сериализаторов и фильтров
Адаптация функции рекомендации пользоваталей на проект
Создание ручек для просмотра навыков в формате списка и дерева

## Дополнительная информация

В следующий раз нужно убрать старые key_skills у пользователей и required_skills_old у вакансий, сейчас они остались мертвым грузом

2024-03-03 15:50 UTC, Yakser requested changes

2024-03-03 15:50 UTC, Yakser commented on core/migrations/0011_auto_20240128_2214.py
> +        if (category not in categories_set) and not SpecializationCategory.objects.filter(name=category).exists():
скобки тут кажется лишние

2024-03-03 15:50 UTC, Yakser commented on core/migrations/0011_auto_20240128_2214.py
> +        if (category not in categories_set) and not SpecializationCategory.objects.filter(name=category).exists():
но могу напиздеть

2024-03-03 15:50 UTC, Yakser commented on core/migrations/0014_migrate_key_skills_to_skills.py
> +custom_user_content_type = ContentType.objects.get_for_model(CustomUser)
вот тут я так понимаю падает миграция

2024-03-03 16:01 UTC, Yakser requested changes

2024-03-04 13:43 UTC, IgorDuino commented on core/models.py
> +        return self.name
Чтобы в админке нормально отображалось сделал так, давай тогда уж repr и str сделаю тут, потом в остальных местах доделаем

2024-03-04 13:53 UTC, IgorDuino commented on core/models.py
> +        verbose_name_plural = "Навыки"
Я знаю, только в админке тогда будет отображаться не Навыки а SkillToObjetcs

2024-03-04 13:55 UTC, IgorDuino commented on procollab/urls.py
> +    path("core/", include("core.urls", namespace="core")),
не понимаю почему их надо утащить, скилы используются для вакансий в той де степени сколько для юзеров

2024-03-04 13:56 UTC, IgorDuino commented on core/urls.py
> +from django.urls import path
В юзеров и вакансии это нелогично. Отдельное приложение - ок

2024-03-04 13:56 UTC, IgorDuino commented on projects/helpers.py
> +        if user == project.leader or user.skills_count < 1:
какая разница?)

2024-03-04 16:09 UTC, IgorDuino commented on vacancy/serializers.py
> +class RequiredSkillsWriteSerializerMixin(RequiredSkillsSerializerMixin):
Не обрабатывается добавление навыков (POST, PUT, PATCH required_skills_ids игнор) (в users работает)

2024-03-04 19:04 UTC, IgorDuino commented on projects/helpers.py
> +        if user_skills.intersection(all_needed_skills):
вопрос только сахарного синтаксиса, слова всегда читаемее

2024-03-04 19:05 UTC, IgorDuino commented on projects/helpers.py
> +        print(user_skills, all_needed_skills)
убраль)

2024-03-04 19:05 UTC, IgorDuino commented on core/urls.py
> +from django.urls import path
Открыл таску на будущее

2024-03-04 19:05 UTC, IgorDuino commented on procollab/urls.py
> +    path("core/", include("core.urls", namespace="core")),
Открыл таску на будущее

2024-03-04 19:06 UTC, IgorDuino commented on core/migrations/0014_migrate_key_skills_to_skills.py
> +custom_user_content_type = ContentType.objects.get_for_model(CustomUser)
Исправил

2024-03-04 19:08 UTC, Yakser commented on core/models.py
> +        return self.name
хорошо, так даже лучше)

2024-03-04 19:08 UTC, Yakser commented on core/models.py
> +        verbose_name_plural = "Навыки"
ну да, можно как то обыграть это и переименовать по другому чтобы ясно было что это крепилка навыка

2024-03-04 19:18 UTC, IgorDuino commented on core/serializers.py
> +class STOSerializer(serializers.ModelSerializer):
done

2024-03-04 19:21 UTC, IgorDuino commented on projects/helpers.py
> +        if user_skills.intersection(all_needed_skills):
done

2024-03-04 19:29 UTC, Yakser commented on users/filters.py
> +        skills_filter = Q()
прикольно

2024-03-04 19:29 UTC, Yakser commented on users/models.py
> +        return skills
```python
return [sto.skill for sto in self.skills.all()]
```
имхо легче читается + нет кучи аппендов

2024-03-04 19:29 UTC, Yakser commented on users/serializers.py
> +            for skill_id in validated_data["skills_ids"]:
у validated_data нет метода .get?

если есть можно убрать иф и написать `for skill_id in validated_data.get("skills_ids", []):`

2024-03-04 19:29 UTC, Yakser commented on vacancy/models.py
> +        required_skills: A GenericRelation ша required skills for the vacancy.
GenericRelation ша.... хавхпхваап

2024-03-04 19:31 UTC, IgorDuino commented on users/serializers.py
> -    key_skills = KeySkillsField(required=False)
поле в БД я не трогал, а всё что передает бек мы завтра с имой разом переделаем, чтобы фронт всё правильно передавал

2024-03-04 19:35 UTC, IgorDuino commented on users/serializers.py
> +            for skill_id in validated_data["skills_ids"]:
Тут это можно поменять, в patch если что нельзя, чтобы при передачи required_skills_ids = [] мы зашлм в условие и удалили все sto, а не просто скипнули это.
Здесь поменяю ок

2024-03-04 19:36 UTC, IgorDuino commented on vacancy/models.py
> +        required_skills: A GenericRelation ша required skills for the vacancy.
done

2024-03-04 19:41 UTC, merged